name: All daily builds

on:
  schedule:
    - cron: '0 0 * * *'


jobs:
  all-daily-compilers:
    name: Build daily compilers
    runs-on: [ 'ce','ubuntu' ]
    strategy:
      fail-fast: false
      matrix:
        # IMPORTANT: when you add a build here you must also add an entry in remove_old_compilers.sh
        # These are slowly replacing the ones in admin-daily-builds.sh
        include:
          - { image: clang, build_name: llvm, command: build.sh, build: llvm-trunk }
          - { image: clang, build_name: clang, command: build.sh, build: trunk }
          - { image: gcc, build_name: gcc, command: build.sh, build: trunk }
          - { image: gcc, build_name: gcc_contracts, command: build.sh, build: lock3-contracts-trunk }
          - { image: gcc, build_name: gcc_contract_labels, command: build.sh, build: lock3-contract-labels-trunk }
          - { image: gcc, build_name: gcc_modules, command: build.sh, build: cxx-modules-trunk }
          - { image: gcc, build_name: gcc_coroutines, command: build.sh, build: cxx-coroutines-trunk }
          - { image: gcc, build_name: gcc_gccrs_master, command: build.sh, build: gccrs-master }

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/daily-build
        with:
          image: ${{ matrix.image }}
          build_name: ${{ matrix.build_name }}
          command: ${{ matrix.command }}
          build: ${{ matrix.build }}
