name: One-off daily build

on:
  workflow_dispatch:
    inputs:
      image:
        description: Docker image (gcc, clang...)
        required: true
        default: gcc
      build_name: # TODO this is probably dangerous...
        description: Name of the build (gcc, gcc_contracts...)
        required: true
        default: gcc
      command:
        description: Command to run (build.sh...)
        required: true
        default: build.sh
      build:
        description: Target to build (trunk, llvm-trunk...)
        required: true
        default: trunk

jobs:
  one-off-build:
    name: Build ${{ inputs.build_name }}
    runs-on: [ 'ce','ubuntu' ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/daily-build.yml
        with:
          image: ${{ inputs.image }}
          build_name: ${{ inputs.build_name }}
          command: ${{ inputs.command }}
          build: ${{ inputs.build }}
