name: Misc builder

on:
  workflow_dispatch:
    inputs:
      buildname:
        description: 'Build name (name part of the build script)'
        default: 'erlang'
        required: true
      version:
        description: 'Version'
        default: '24.1.6'
        required: true

jobs:
  buildmisc:
    name: Buildmisc ${{ github.event.inputs.buildname }} ${{ github.event.inputs.version }}
    runs-on: ['admin']

    steps:
    - name: Update infra
      run: cd /home/ubuntu/infra && git pull
    - name: Build the thing
      run: /home/ubuntu/infra/one-off-misc.sh ${{ github.event.inputs.compilertype }} "build-${{ github.event.inputs.buildname }}.sh" ${{ github.event.inputs.version }}
