name: Squashfs-ify the compilers

on:
  workflow_dispatch:
    inputs:
      squash:
        description: Things to squash (empty means all)
        default: ''
        required: false
jobs:
  squash:
    runs-on: [ 'self-hosted', 'ce', 'ubuntu' ]
    steps:
      - name: Start from a clean directory
        uses: AutoModality/action-clean@v1.1.0
      - uses: actions/checkout@v2
      - name: Test
        run: |
          sudo apt install -y python3.8-venv squashfs-tools
          make ce
          bin/ce_install squash ${{ inputs.squash }}
